return {
	-- "xiyaowong/transparent.nvim",
	--
	-- config = function()
	-- 	require("transparent").setup({ -- Optional, you don't have to run setup.
	-- 		groups = { -- table: default groups
	-- 			"Normal",
	-- 			"NormalNC",
	-- 			"Comment",
	-- 			"Constant",
	-- 			"Special",
	-- 			"Identifier",
	-- 			"Statement",
	-- 			"PreProc",
	-- 			"Type",
	-- 			"Underlined",
	-- 			"Todo",
	-- 			"String",
	-- 			"Function",
	-- 			"Conditional",
	-- 			"Repeat",
	-- 			"Operator",
	-- 			"Structure",
	-- 			"LineNr",
	-- 			"NonText",
	-- 			"SignColumn",
	-- 			"CursorLine",
	-- 			"CursorLineNr",
	-- 			"StatusLine",
	-- 			"StatusLineNC",
	-- 			"EndOfBuffer",
	-- 		},
	-- 		extra_groups = {
 --        "lualine_c_normal",
 --        "lualine_c_insert",
 --        "lualine_c_inactive",
 --        "lualine_c_diagnostics_hint_normal",
 --        "lualine_c_diagnostics_error_normal",
 --        "lualine_c_diagnostics_warn_normal",
 --        "lualine_c_diagnostics_info_normal",
 --        "lualine_c_diagnostics_hint_insert",
 --        "lualine_c_diagnostics_error_insert",
 --        "lualine_c_diagnostics_warn_insert",
 --        "lualine_c_diagnostics_info_insert",
 --        "lualine_c_diagnostics_hint_visual",
 --        "lualine_c_diagnostics_error_visual",
 --        "lualine_c_diagnostics_warn_visual",
 --        "lualine_c_diagnostics_info_visual",
 --      }, -- table: additional groups that should be cleared
	-- 		exclude_groups = {--[[  "CursorLine" ,]]"CursorLineNr" }, -- table: groups you don't want to clear
	-- 	})
	-- end,
}
